services:
  contacts:
    build: .
    container_name: contacts
    environment:
      CONTACTS_DB_HOST: postgres
      CONTACTS_DB_PORT: 5432
      CONTACTS_DB_URL: postgres://root@postgres/root?sslmode=disable
      CONTACTS_DB_MIGRATIONS: /migrations
    ports:
      - "8888:8080"

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: root
  php:
    build: 
      context: .
    image: durdahl/seascan-master
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=seascan-master-sql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=seascan
    volumes:
      - .:/var/www/html
    ports:
      - "30001:80"
    container_name: seascan-master
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=seascan
    container_name: seascan-master-sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=seascan-master-sql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: seascan-phpmyadmin
networks:
  frontend:
  backend: