version: "3.2"
services:
  php:
    build: 
      context: .
    image: team10/seascan-master
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=seascan-master-sql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=seascan
    volumes:
      - .:/var/www/html
    ports:
      - "30001:80"
    container_name: seascan-master
  mysql:
    image: mysql:5.7
    # platform: linux/amd64
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=seascan
    container_name: seascan-master-sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=seascan-master-sql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: seascan-phpmyadmin
networks:
  frontend:
  backend:
