jobs:
  install_composer_packages:
    executor: php/default
    steps:
      - checkout
      - php/install-composer:
          install-version: 1.10.16
      - php/install-packages
orbs:
  php: circleci/php@x.y
version: 2.1
workflows:
  install:
    jobs:
      - install_composer_packages