version: 2.1
jobs:

  build:
    docker:
      # - image: cimg/base:stable
      - image: php:7.2-apache
    steps:
      - checkout
      - run: 
          name: get version info
          command: |
            docker --version
            docker-compose --version
            pwd
            ls
      - run:
          name: "run docker"
          command: |
            set -x
            cd ../
            ls

      - run:
          name: "build img"
          command: |
            sudo docker build . -t durdahl/seascan-master
            
      # - run:
      #     name: "run compose services"
      #     command: |
      #       set -x
      #       docker-compose up --build

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - build