version: 2.1
jobs:
  build:
    machine: true
        # docker:
        #   - image: cimg/base:stable
    steps:
      - checkout
      # - setup_remote_docker: 
      #     version: 20.10.7
      - run: 
          name: create image
          command: |
            ls
            sudo docker build . -t durdahl/seascan-master
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up --build

  tests:
    steps:
      - run:
          name: run phpUnit tests
          command: |
            pwd
            ls
            sudo ./vendor/bin/phpunit --testdox
    
workflows:
  test-workflow:
    jobs:
      - build
      - test