version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: get version info
          command: |
            docker --version
            docker-compose --version
            pwd
            ls
            cd ../
            ls
            cd ../
            ls
            ls -l /usr/local/bin/docker-compose
      - run:
          name: "run docker"
          command: |
            set -x
            sudo apt-get remove docker-compose

      # - run:
      #     name: "build img"
      #     command: |
      #       set -x
      #       docker build . -t durdahl/seascan-master
            
      # - run:
      #     name: "run compose services"
      #     command: |
      #       set -x
      #       docker-compose up --build

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - build