version: 2.1
jobs:
  build:
    machine: true
        # docker:
        #   - image: cimg/base:stable
    steps:
      - checkout
      # - setup_remote_docker: 
      #     version: 20.10.7
      - run: 
          name: create image
          command: |
            ls
            sudo docker build . -t durdahl/seascan-master
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up --build

  install_php:
    docker:
      - image: 'cimg/base:edge'
    steps:
      - checkout
      - php/install-php:
          version: '7.3'
      - run:
          name: unit test maybe
          command: |
            pwd
            ls
            sudo ./vendor/bin/phpunit --testdox
  orbs:
    php: circleci/php@x.y
    version: 2.1

workflows:
  test-workflow:  
    jobs:
      - install_php
      - build
      